"""add default plans

Revision ID: 6c27c4b17ebc
Revises: 193a82daf1a4
Create Date: 2025-05-16 10:49:41.986170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c27c4b17ebc"
down_revision: Union[str, None] = "193a82daf1a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    meta = sa.MetaData()
    meta.reflect(bind=op.get_bind())
    organization_plans = meta.tables["organization_plans"]

    op.bulk_insert(
        organization_plans,
        [
            {
                "name": "TRIAL",
                "description": "TRIAL Plan",
                "price": 0,
                "duration": None,
                "recoverable": False,
            },
            {
                "name": "PAID",
                "description": "Paid Plan",
                "price": 10000,
                "duration": 15,
                "recoverable": True,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
